name: p2p-command

on:
  workflow_call:
    secrets:
      env_vars:
        required: false
    outputs:
      version:
        description: "The latest image in the registry"
        value: ${{ jobs.get-latest-image.outputs.version }}
    inputs:
      registry-path:
        required: false
        type: string
        default: 'extended-test'
      image-name:
        required: true
        type: string
      dry-run:
        required: false
        type: boolean
        default: false
      region:
        required: false
        type: string
        default: europe-west2
      working-directory:
        required: false
        type: string
        default: '.'
      environment:
        required: true
        type: string

jobs:
  get-latest-image:
    name: get-latest-image
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get-latest-image.outputs.version }}
    environment: ${{ fromJson(inputs.environment).include[0]['deploy_env'] }}
    env:
      BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
      INTERNAL_SERVICES_DOMAIN: ${{ vars.INTERNAL_SERVICES_DOMAIN }}
      DPLATFORM: ${{ vars.DPLATFORM }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
      REGION: ${{ inputs.region }}
      REGISTRY: ${{ inputs.region }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/tenant/${{ vars.TENANT_NAME }}
      SERVICE_ACCOUNT: p2p-${{ vars.TENANT_NAME }}@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com
      GITHUB_ENV: ${{ fromJson(inputs.environment).include[0]['deploy_env'] }}
      TENANT_NAME: ${{ vars.TENANT_NAME }}
      WORKLOAD_IDENTITY_PROVIDER: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/p2p-${{ vars.TENANT_NAME }}/providers/p2p-${{ vars.TENANT_NAME }}
      REGISTRY_PATH: ${{ inputs.registry-path }}
      IMAGE_NAME: ${{ inputs.image-name }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: print env context
        run: |
          yq -p=json -C <<EOT
          ${{ toJSON(env) }}
          EOT

      - name: Authenticate to Google Cloud
        id: auth
        if: inputs.dry-run == false
        uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}
          token_format: access_token
          access_token_lifetime: 600s

      - name: Get latest image
        id: get-latest-image
        env:
          DRY_RUN: ${{ inputs.dry-run }}
        working-directory: ${{ inputs.working-directory }}
        run: |
            set -o pipefail
            [ $DRY_RUN == false ] && version=$(gcloud artifacts docker images list ${REGISTRY}/${REGISTRY_PATH}/${IMAGE_NAME} --include-tags --sort-by=~buildTime --format=json 2>/dev/null | jq -r '.[].tags[]' | jq -Rrn '[inputs] | sort_by(
              # extract name and version
              match("[0-9]+[0-9.]*";"").offset as $version_index
              | .[:$version_index] as $name
              | .[$version_index:]
              # ignore build
              | split("+")[0]
              # extract version core and pre-release as arrays of numbers and strings
              | split("-")
              | (.[0] | split(".") | map(tonumber? // .)) as $version_core
              | (.[1:] | join("-") | split(".") | map(tonumber? // .)) as $pre_release
              # sort by name
              | $name,
              # sort by version core
              $version_core,
              # pre-release versions have a lower precedence than the associated normal version
              ($pre_release | length)==0,
              # sort by pre-release
              $pre_release
            ) | reverse | .[0]')
            [ $? -gt 0 ] && [ $DRY_RUN == false ] && echo "exiting" && exit 1
            [ $DRY_RUN == true ] && version="0.0.0"
            echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: "Output version: ${{ steps.get-latest-image.outputs.version }}"
        id: outputversion
        shell: bash
        run: |
          echo "Output version: ${{ steps.get-latest-image.outputs.version }}"
