on:
  workflow_call:
    secrets:
      env_vars:
        required: false
      container_registry_user:
        required: false
      container_registry_pat:
        required: false
      container_registry_url:
        required: false
    inputs:
      source:
        required: false
        type: string
        default: ${{ vars.EXTENDED_TEST }}
      destination:
        required: false
        type: string
        default: ${{ vars.PROD }}
      dry-run:
        required: false
        type: boolean
        default: false
      region:
        required: false
        type: string
        default: europe-west2
      main-branch:
        required: false
        type: string
        default: 'refs/heads/main'
      working-directory:
        required: false
        type: string
        default: '.'
      version:
        required: true
        type: string
      version-prefix:
        required: false
        type: string
        default: 'v'
      corectl-version:
        required: false
        type: string

jobs:
  run-tests:
    uses: ./.github/workflows/p2p-execute-command.yaml
    if: success() && (github.ref == inputs.main-branch )
    secrets:
      env_vars: ${{ secrets.env_vars }}
      container_registry_user: ${{ secrets.container_registry_user }}
      container_registry_url: ${{ secrets.container_registry_url }}
      container_registry_pat: ${{ secrets.container_registry_pat }}
    strategy:
      matrix: ${{ fromJSON(inputs.source ) }}
      fail-fast: false
    with:
      command: p2p-extended-test
      github_env: ${{ matrix.deploy_env }}
      version: ${{ inputs.version }}
      dry-run: ${{ inputs.dry-run }}
      working-directory: ${{ inputs.working-directory }}
      checkout-version: ${{ inputs.version-prefix }}${{ inputs.version }}

  promote:
    uses: ./.github/workflows/p2p-promote-image.yaml
    if: success() && (github.ref == inputs.main-branch)
    needs: [run-tests]
    secrets:
      env_vars: ${{ secrets.env_vars }}
    strategy:
      matrix: ${{ fromJSON(inputs.destination) }}
      fail-fast: false
    with:
      source_matrix: ${{ inputs.source }}
      dest_github_env: ${{ matrix.deploy_env }}
      promotion-stage: prod
      version: ${{ inputs.version  }}
      dry-run: ${{ inputs.dry-run }}
      working-directory: ${{ inputs.working-directory }}
      checkout-version: ${{ inputs.version-prefix }}${{ inputs.version }}
      corectl-version: ${{ inputs.corectl-version }}
